'''Each new term in the Fibonacci sequence is generated by adding the
   previous two terms. By starting with 1 and 2, the first 10 terms will
   be:

   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

   By considering the terms in the Fibonacci sequence whose values do 
   not exceed four million, find the sum of the even-valued terms.
'''

# My solution:
fib_sequence = [1, 2]
num1, num2 = 1, 2
num3 = num1 + num2

result = 0

while num3 <= 4000000:
    
    fib_sequence.append(num3)
    num1, num2 = num2, num3
    num3 = num1 + num2

print(sum(num for num in fib_sequence if num % 2 == 0))
